export class FactorioIcon {
  src: string;
  text?: string;
  name: string;

  constructor(src: string, text?: string, name?: string) {
    this.src = src;
    this.text = text;
    this.name = name || '';
  }
}

export enum FactorioIconIds {
  'Accumulator' = 'Accumulator',
  'Advanced_circuit' = 'Advanced_circuit',
  'Advanced_oil_processing' = 'Advanced_oil_processing',
  'Assembling_machine_1' = 'Assembling_machine_1',
  'Assembling_machine_2' = 'Assembling_machine_2',
  'Assembling_machine_3' = 'Assembling_machine_3',
  'Automation_science_pack' = 'Automation_science_pack',
  'Battery' = 'Battery',
  'Beacon' = 'Beacon',
  'Boiler' = 'Boiler',
  'Burner_inserter' = 'Burner_inserter',
  'Cargo_wagon' = 'Cargo_wagon',
  'Centrifuge' = 'Centrifuge',
  'Chemical_plant' = 'Chemical_plant',
  'Chemical_science_pack' = 'Chemical_science_pack',
  'Coal' = 'Coal',
  'Copper_cable' = 'Copper_cable',
  'Copper_ore' = 'Copper_ore',
  'Copper_plate' = 'Copper_plate',
  'Crude_oil_barrel' = 'Crude_oil_barrel',
  'Crude_oil' = 'Crude_oil',
  'Efficiency_module_3' = 'Efficiency_module_3',
  'Electric_engine_unit' = 'Electric_engine_unit',
  'Electric_furnace' = 'Electric_furnace',
  'Electronic_circuit' = 'Electronic_circuit',
  'Empty_barrel' = 'Empty_barrel',
  'Engine_unit' = 'Engine_unit',
  'Express_transport_belt' = 'Express_transport_belt',
  'Fast_inserter' = 'Fast_inserter',
  'Fast_transport_belt' = 'Fast_transport_belt',
  'Filter_inserter' = 'Filter_inserter',
  'Firearm_magazine' = 'Firearm_magazine',
  'Fluid_wagon' = 'Fluid_wagon',
  'Flying_robot_frame' = 'Flying_robot_frame',
  'Grenade' = 'Grenade',
  'Heat_exchanger' = 'Heat_exchanger',
  'Heavy_oil' = 'Heavy_oil',
  'Inserter_capacity_bonus_(research)' = 'Inserter_capacity_bonus_(research)',
  'Inserter' = 'Inserter',
  'Iron_gear_wheel' = 'Iron_gear_wheel',
  'Iron_ore' = 'Iron_ore',
  'Iron_plate' = 'Iron_plate',
  'Iron_stick' = 'Iron_stick',
  'Lab' = 'Lab',
  'Light_oil' = 'Light_oil',
  'Logistic_science_pack' = 'Logistic_science_pack',
  'Long-handed_inserter' = 'Long-handed_inserter',
  'Low_density_structure' = 'Low_density_structure',
  'Lubricant' = 'Lubricant',
  'Military_science_pack' = 'Military_science_pack',
  'Nuclear_fuel' = 'Nuclear_fuel',
  'Nuclear_reactor' = 'Nuclear_reactor',
  'Offshore_pump' = 'Offshore_pump',
  'Oil_refinery' = 'Oil_refinery',
  'Petroleum_gas' = 'Petroleum_gas',
  'Piercing_rounds_magazine' = 'Piercing_rounds_magazine',
  'Pipe' = 'Pipe',
  'Plastic_bar' = 'Plastic_bar',
  'Processing_unit' = 'Processing_unit',
  'Production_science_pack' = 'Production_science_pack',
  'Productivity_module_3' = 'Productivity_module_3',
  'Productivity_module' = 'Productivity_module',
  'Pump' = 'Pump',
  'Rocket_control_unit' = 'Rocket_control_unit',
  'Rocket_fuel' = 'Rocket_fuel',
  'Rocket_silo' = 'Rocket_silo',
  'Solar_panel' = 'Solar_panel',
  'Solid_fuel' = 'Solid_fuel',
  'Space_science_pack' = 'Space_science_pack',
  'Speed_module_2' = 'Speed_module_2',
  'Speed_module_3' = 'Speed_module_3',
  'Speed_module' = 'Speed_module',
  'Stack_filter_inserter' = 'Stack_filter_inserter',
  'Stack_inserter' = 'Stack_inserter',
  'Steam_turbine' = 'Steam_turbine',
  'Steam' = 'Steam',
  'Steel_chest' = 'Steel_chest',
  'Steel_furnace' = 'Steel_furnace',
  'Stone_brick' = 'Stone_brick',
  'Stone_furnace' = 'Stone_furnace',
  'Storage_tank' = 'Storage_tank',
  'Straight_rail' = 'Straight_rail',
  'Sulfur' = 'Sulfur',
  'Sulfuric_acid' = 'Sulfuric_acid',
  'Transport_belt' = 'Transport_belt',
  'Uranium_fuel_cell' = 'Uranium_fuel_cell',
  'Uranium_ore' = 'Uranium_ore',
  'Uranium_rounds_magazine' = 'Uranium_rounds_magazine',
  'Uranium-235' = 'Uranium-235',
  'Uranium-238' = 'Uranium-238',
  'Utility_science_pack' = 'Utility_science_pack',
  'Wall' = 'Wall',
  'Water' = 'Water',
  'Wood' = 'Wood',
}
