import { RawData } from 'app/models/Data.model';
import { ProductivityModulePayoffsData } from 'app/models/ProductivityModulePayoffsData.model';
import { FactorioIcons } from 'app/shared/factorio-icons.enum';
import { NavData, newNavData } from 'app/shared/nav-data/nav-data.model';

export const PRODUCTIVITY_MODULE_PAYOFFS_SHEET_NAV: NavData = newNavData(
  'Productivity Module Payoffs',
  FactorioIcons.Icons_ProductivityModule3
);

export const PRODUCTIVITY_MODULE_PAYOFFS_DATA: RawData<ProductivityModulePayoffsData> =
  {
    cheatSheet: {
      title: PRODUCTIVITY_MODULE_PAYOFFS_SHEET_NAV.title,
      iconId: PRODUCTIVITY_MODULE_PAYOFFS_SHEET_NAV.sheetIconId,
    },
    data: {
      payoffs: [
        {
          productIconId: FactorioIcons.Icons_RocketPart,
          description: '',
          payoff_speed_prod: '00:01:19',
          payoff_prod: '00:02:36',
          payoff_beacon_4x4: '00:01:13',
          payoff_beacon_12: '00:01:43',
        },
        {
          productIconId: FactorioIcons.Icons_Lab,
          description: 'Late Game',
          payoff_speed_prod: '00:36:04',
          payoff_prod: '00:34:47',
          payoff_beacon_4x4: '00:10:34',
          payoff_beacon_12: '00:26:45',
        },
        {
          productIconId: FactorioIcons.Icons_UtilitySciencePack,
          description: 'Yellow Science',
          payoff_speed_prod: '00:44:41',
          payoff_prod: '01:27:58',
          payoff_beacon_4x4: '00:12:10',
          payoff_beacon_12: '00:24:39',
        },
        {
          productIconId: FactorioIcons.Icons_ProductionSciencePack,
          description: 'Purple Science',
          payoff_speed_prod: '00:46:45',
          payoff_prod: '01:32:03',
          payoff_beacon_4x4: '00:12:44',
          payoff_beacon_12: '00:25:48',
        },
        {
          productIconId: FactorioIcons.Icons_ProcessingUnit,
          description: 'Blue Circuit',
          payoff_speed_prod: '01:27:50',
          payoff_prod: '02:52:55',
          payoff_beacon_4x4: '00:23:54',
          payoff_beacon_12: '00:48:28',
        },
        {
          productIconId: FactorioIcons.Fluid_SulfuricAcid,
          description: '',
          payoff_speed_prod: '01:30:05',
          payoff_prod: '02:11:02',
          payoff_beacon_4x4: '00:26:50',
          payoff_beacon_12: '00:59:50',
        },
        {
          productIconId: FactorioIcons.Icons_ElectronicCircuit,
          description: 'Green Circuit',
          payoff_speed_prod: '02:04:28',
          payoff_prod: '04:05:02',
          payoff_beacon_4x4: '00:33:53',
          payoff_beacon_12: '01:08:41',
        },
        {
          productIconId: FactorioIcons.Icons_MilitarySciencePack,
          description: 'Blue Science',
          payoff_speed_prod: '02:07:00',
          payoff_prod: '04:10:02',
          payoff_beacon_4x4: '00:34:34',
          payoff_beacon_12: '01:10:05',
        },
        // Deprecated https://wiki.factorio.com/Archive:Rocket_control_unit
        // {
        //   productIconId: FactorioIcons.Icons_RocketControlUnit,
        //   description: '',
        //   payoff_speed_prod: '02:20:00',
        //   payoff_prod: '04:35:38',
        //   payoff_beacon_4x4: '00:38:06',
        //   payoff_beacon_12: '01:17:15',
        // },
        {
          productIconId: FactorioIcons.Icons_IronGearWheel,
          description: '',
          payoff_speed_prod: '02:35:35',
          payoff_prod: '05:06:18',
          payoff_beacon_4x4: '00:42:21',
          payoff_beacon_12: '01:25:51',
        },
        {
          productIconId: FactorioIcons.Icons_PlasticBar,
          description: '',
          payoff_speed_prod: '04:15:15',
          payoff_prod: '06:11:16',
          payoff_beacon_4x4: '01:16:02',
          payoff_beacon_12: '02:49:31',
        },
        {
          productIconId: FactorioIcons.Icons_Sulfur,
          description: '',
          payoff_speed_prod: '04:15:15',
          payoff_prod: '06:11:16',
          payoff_beacon_4x4: '01:16:02',
          payoff_beacon_12: '02:49:31',
        },
        {
          productIconId: FactorioIcons.Icons_ChemicalSciencePack,
          description: 'Blue Science',
          payoff_speed_prod: '05:03:15',
          payoff_prod: '09:57:02',
          payoff_beacon_4x4: '01:22:32',
          payoff_beacon_12: '02:47:20',
        },
        {
          productIconId: FactorioIcons.Icons_CopperCable,
          description: '',
          payoff_speed_prod: '05:11:09',
          payoff_prod: '10:12:35',
          payoff_beacon_4x4: '01:24:41',
          payoff_beacon_12: '02:51:41',
        },
        {
          productIconId: FactorioIcons.Icons_IronStick,
          description: '',
          payoff_speed_prod: '05:11:09',
          payoff_prod: '10:12:35',
          payoff_beacon_4x4: '01:24:41',
          payoff_beacon_12: '02:51:41',
        },
        {
          productIconId: FactorioIcons.Icons_FlyingRobotFrame,
          description: '',
          payoff_speed_prod: '05:20:47',
          payoff_prod: '10:31:32',
          payoff_beacon_4x4: '01:27:19',
          payoff_beacon_12: '02:57:00',
        },
        {
          productIconId: FactorioIcons.Icons_LowDensityStructure,
          description: '',
          payoff_speed_prod: '05:31:54',
          payoff_prod: '10:53:25',
          payoff_beacon_4x4: '01:30:20',
          payoff_beacon_12: '03:03:08',
        },
        {
          productIconId: FactorioIcons.Icons_AdvancedCircuit,
          description: '',
          payoff_speed_prod: '06:13:23',
          payoff_prod: '12:15:06',
          payoff_beacon_4x4: '01:41:38',
          payoff_beacon_12: '03:26:02',
        },
        {
          productIconId: FactorioIcons.Icons_ElectricEngineUnit,
          description: '',
          payoff_speed_prod: '06:41:29',
          payoff_prod: '13:10:26',
          payoff_beacon_4x4: '01:49:17',
          payoff_beacon_12: '03:41:32',
        },
        {
          productIconId: FactorioIcons.Icons_LogisticSciencePack,
          description: 'Green Science',
          payoff_speed_prod: '08:53:24',
          payoff_prod: '17:30:09',
          payoff_beacon_4x4: '02:25:11',
          payoff_beacon_12: '04:54:19',
        },
        {
          productIconId: FactorioIcons.Icons_Battery,
          description: '',
          payoff_speed_prod: '09:27:12',
          payoff_prod: '13:45:02',
          payoff_beacon_4x4: '02:48:58',
          payoff_beacon_12: '06:16:42',
        },
        {
          productIconId: FactorioIcons.Icons_EngineUnit,
          description: '',
          payoff_speed_prod: '11:31:27',
          payoff_prod: '22:41:18',
          payoff_beacon_4x4: '03:08:12',
          payoff_beacon_12: '06:21:32',
        },
        {
          productIconId: FactorioIcons.Icons_StoneBrick,
          description: '',
          payoff_speed_prod: '12:06:01',
          payoff_prod: '11:40:06',
          payoff_beacon_4x4: '03:32:52',
          payoff_beacon_12: '08:58:39',
        },
        {
          productIconId: FactorioIcons.Icons_AutomationSciencePack,
          description: 'Red Science',
          payoff_speed_prod: '17:17:11',
          payoff_prod: '34:01:57',
          payoff_beacon_4x4: '04:42:18',
          payoff_beacon_12: '09:32:18',
        },
        {
          productIconId: FactorioIcons.Icons_UraniumProcessing,
          description: '',
          payoff_speed_prod: '18:09:02',
          payoff_prod: '17:30:09',
          payoff_beacon_4x4: '05:19:18',
          payoff_beacon_12: '13:27:59',
        },
        {
          productIconId: FactorioIcons.Icons_Explosives,
          description: '',
          payoff_speed_prod: '20:25:10',
          payoff_prod: '29:42:04',
          payoff_beacon_4x4: '06:04:59',
          payoff_beacon_12: '13:33:41',
        },
        {
          productIconId: FactorioIcons.Icons_CopperPlate,
          description: '',
          payoff_speed_prod: '24:12:03',
          payoff_prod: '23:20:11',
          payoff_beacon_4x4: '07:05:44',
          payoff_beacon_12: '17:57:18',
        },
        {
          productIconId: FactorioIcons.Icons_IronPlate,
          description: '',
          payoff_speed_prod: '24:12:03',
          payoff_prod: '23:20:11',
          payoff_beacon_4x4: '07:05:44',
          payoff_beacon_12: '17:57:18',
        },
        {
          productIconId: FactorioIcons.Icons_SteelPlate,
          description: '',
          payoff_speed_prod: '24:12:03',
          payoff_prod: '23:20:11',
          payoff_beacon_4x4: '07:05:44',
          payoff_beacon_12: '17:57:18',
        },
        {
          productIconId: FactorioIcons.Icons_RocketFuel,
          description: '',
          payoff_speed_prod: '24:53:32',
          payoff_prod: '49:00:24',
          payoff_beacon_4x4: '06:46:31',
          payoff_beacon_12: '13:44:07',
        },
      ],
    },
  };
